import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

import dynamic from 'next/dynamic'
import { draftMode } from 'next/headers'
import { token } from '../lib/sanity.fetch'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

const PreviewProvider = dynamic(() => import('@/components/PreviewProvider'))

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* Header */}
        <Header />

        {draftMode().isEnabled ? (
          <PreviewProvider token={token}>{children}</PreviewProvider>
        ) : (
          children
        )}

        {/* Footer */}
        <Footer />
      </body>
    </html>
  )
}
