import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

import dynamic from 'next/dynamic'
import { draftMode } from 'next/headers'
import { token } from '../lib/sanity.fetch'
import { ThemeProvider } from '@/components/ThemeProvider'

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

const PreviewProvider = dynamic(() => import('@/components/PreviewProvider'))

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {/* Header */}
          <Header />

          {draftMode().isEnabled ? (
            <PreviewProvider token={token}>{children}</PreviewProvider>
          ) : (
            children
          )}

          {/* Footer */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
